core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from rest_framework.routers import DefaultRouter


from product import views

router = DefaultRouter()
router.register(r"category", views.CategoryViewSet)
router.register(r"brand", views.BrandViewSet)
router.register(r"product", views.ProductViewSet)


def home(request):
    return render(request, 'home.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('users.urls', namespace='users')),
    path('', home, name='home'),
    path('', include('product.urls', namespace='product'), name='home'),
    path("api/", include(router.urls)),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/docs/', SpectacularSwaggerView.as_view(url_name='schema')),
]

users/urls.py
from django.urls import path
from .views import profile_view, profile_update_view

app_name = 'users'
urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('profile-update/', profile_update_view, name='profile-update'),
]

templates/home.html
{% extends 'index.html' %} {% block css %} {% endblock css %} {% load crispy_forms_tags %} {%block title%}Welcome Psy Web{% endblock title %}
{% block content %}
<div class="container">
  <div class="row my-3">
    <div class="col-md-8">
      <div class="flask-message">
        {%if messages %} {% for message in messages%}
        <div class="alert alert-{{message.tags}}">
          {% if user.is_authenticated %}
          {{request.user}} {{message}}
          {% else %}
          {{message}}
          {% endif %}
        </div>
      {% endfor %} {%endif %}
      </div>
      <div class="book-section border-bottom p-4">
        <a href="{% url 'blog:create_book'%}">Create A Book</a>
        {% if books%}
        {% for book in books %}
        <div>
          {{book.title}}
        </div>
        {% endfor %}
        {% endif%}
      </div>
      <div class="article-section border-bottom p-4">
        <a href="{% url 'blog:create_article'%}">Create An Article</a>
        {% if articles%}
        {% for article in articles %}
        <div>
          <a href="{% url 'blog:article-detail' article.slug %}">{{article.title}}</a>
        </div>
        {% endfor %}
        {% endif%}
      </div>
      <div class="contributor-section border-bottom p-4">
        <a href="{% url 'blog:create_contributor'%}">Create A Contributor</a>
        {% if contributors%}
        {% for contributor in contributors %}
        <div>
          <a href="{% url 'blog:contributor-detail' contributor.slug %}">{{contributor.full_name}}</a>
        </div>
        {% endfor %}
        {% endif%}
      </div>
    </div>
    <div class="col-md-4">

    </div>
  </div>
</div>
{% endblock content %}
{% block JS %} {% endblock JS %}

templates/index.html
{% load static %} {% load i18n %} {% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <script src="https://unpkg.com/htmx.org@1.8.6"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}" />
    {% block css %}
    <!-- <link rel="stylesheet" href="{% static '.css' %}"> -->

    {% endblock css %}
    <title>{% block title %}Document{% endblock title %}</title>
  </head>
  <body>
    {%include 'navbar.html'%}
    <main class="" role="main">
      {% block content %} {% endblock content %}
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
      {% block JS %} {% endblock JS%}
    </main>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/navbar.html
<header class="p-3 text-bg-dark">
    <div class="container">
      <div
        class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start"
      >
        <a
          href="/"
          class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none"
        >
          <svg
            class="bi me-2"
            width="40"
            height="32"
            role="img"
            aria-label="Bootstrap"
          >
            <use xlink:href="#bootstrap" />
          </svg>
        </a>
  
        <ul
          class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"
        >
          <li>
            <a href="{% url 'home' %}" class="nav-link px-2 text-secondary"
              >Home</a
            >
          </li>
          <li><a href="#" class="nav-link px-2 text-white">Test</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>
        {% if page != 'register_page' %}
        <div
          class="text-end d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start"
        >
          {% if user.is_authenticated %}
          <p class="d-flex align-items-center mb-2 mb-lg-0 text-white mx-3">
            <a href="{% url 'users:profile' %}">Hi <small class="text-capitalize">{{ user.username }}</small>!</a>
          </p>
          <a type="button" class="btn btn-outline-light" href="{% url 'account_logout' %}"
            >Log Out</a
          >
          {% else %}
          <a href="{% url 'account_login' %}" class="btn btn-outline-light me-2">
            Login
          </a>
          <a href="{% url 'account_signup' %}" class="btn btn-warning">Sign-up</a>
          {% endif %}
        </div>
        {% endif %}
      </div>
    </div>
  </header>
  