core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from rest_framework.routers import DefaultRouter


from product import views

router = DefaultRouter()
router.register(r"category", views.CategoryViewSet)
router.register(r"brand", views.BrandViewSet)
router.register(r"product", views.ProductViewSet)


def home(request):
    return render(request, 'home.html')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('users.urls', namespace='users')),
    path('', home, name='home'),
    path('', include('product.urls', namespace='product'), name='home'),
    path("api/", include(router.urls)),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/docs/', SpectacularSwaggerView.as_view(url_name='schema')),
]

users/urls.py
from django.urls import path
from .views import profile_view, profile_update_view

app_name = 'users'
urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('profile-update/', profile_update_view, name='profile-update'),
]

users/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
import uuid
from ckeditor.fields import RichTextField
from PIL import Image
# Create your models here.

# class CustomUserManager(BaseUserManager):


class CustomUser(AbstractUser):
    email = models.EmailField(_("email address"), unique=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.username


User = get_user_model()


class Profile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, related_name='user_profile')
    following = models.ManyToManyField(User, related_name='following', blank=True)
    follower = models.ManyToManyField(User, related_name='p_followers', blank=True)
    phone = models.CharField(max_length=30, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    profile_pic = models.ImageField(
        null=True, blank=True, default='users/default.png', upload_to='users/profile')
    date_of_birth = models.DateTimeField(null=True, blank=True)
    gender = models.CharField(max_length=20, null=True,
                              blank=True, choices=(
                                  ('MAN', 'Man'),
                                  ('FEMALE', 'Female'),
                                  ('OTHER', 'Other'),
                              ))
    business_area = models.CharField(null=True, blank=True, max_length=50)
    about = RichTextField(null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.profile_pic.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.profile_pic.path)

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth import get_user_model
from allauth.socialaccount.forms import SignupForm
from .models import Profile
User = get_user_model()


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email',)


class ProfileUpdateForm(forms.ModelForm):
    date_of_birth = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={'type': 'date'}))

    class Meta:
        model = Profile
        fields = ('date_of_birth', 'gender', 'phone', 'address',
                  'profile_pic', 'business_area', 'about',)

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth import get_user_model
# from django.views.generic import TemplateView, DetailView
from .forms import RegistrationForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from .models import Profile
# Create your views here.
User = get_user_model()


# @anonymous_require


class SiteLoginView(SuccessMessageMixin, LoginView):
    redirect_authenticated_user = True
    template_name = 'account/login.html'
    success_url = '/success_url/'
    success_message = "were successfully logged in."


def register(response):
    if response.user.is_authenticated:
        return redirect("blog:home")
    else:
        page = 'register_page'
        if response.method == "POST":
            form = RegistrationForm(response.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                form.save()
                messages.success(response, f'{username} has been created')
                return redirect("blog:home")
        else:
            form = RegistrationForm()

        return render(response, "account/register.html", {"form": form, 'page': page})


@login_required
def profile_update_view(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.user_profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your profile info has been updated')
            return redirect('users:profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.user_profile)
    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile_update.html', context)


@login_required
def profile_view(request):
    profile = request.user.user_profile
    context = {
        'profile': profile
    }
    return render(request, 'users/profile.html', context)

templates/users/profile.html
{% extends '../index.html' %} {% block css %}
<style>
  .gradient-custom-2 {
    /* fallback for old browsers */
    background: #fbc2eb;

    /* Chrome 10-25, Safari 5.1-6 */
    background: -webkit-linear-gradient(
      to right,
      rgba(251, 194, 235, 1),
      rgba(166, 193, 238, 1)
    );

    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    background: linear-gradient(
      to right,
      rgba(251, 194, 235, 1),
      rgba(166, 193, 238, 1)
    );
  }
</style>
{% endblock css %} {% load crispy_forms_tags %} {%block title%}Welcome
{{profile.user}}{% endblock title %}
<div>
  {% block content %}
  <section class="h-100 gradient-custom-2">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-7">
          <div class="card">
            <div
              class="rounded-top text-white d-flex flex-row"
              style="background-color: #000; height: 200px"
            >
              <div class="ms-4 mt-5 d-flex flex-column" style="width: 180px">
                <img
                  src="{{user.user_profile.profile_pic.url}}"
                  alt="Generic placeholder image"
                  class="img-thumbnail mt-5 mb-2"
                  style="width: 180px; height: 180px; z-index: 1; object-fit:cover;"
                />
                <a
                  href="{% url 'users:profile-update' %}"
                  class="btn btn-outline-dark"
                  data-mdb-ripple-color="dark"
                  style="z-index: 1"
                >
                  Edit profile
                </a>
              </div>
              <div class="ms-3" style="margin-top: 130px">
                <h5>@{{request.user.username}}</h5>
                <p>{{user.user_profile.address}}</p>
              </div>
            </div>
            <div class="p-4 text-black" style="background-color: #f8f9fa">
              <div class="d-flex justify-content-end text-center py-1">
                <div>
                  <p class="mb-1 h5">253</p>
                  <p class="small text-muted mb-0">Photos</p>
                </div>
                <div class="px-3">
                  <p class="mb-1 h5">1026</p>
                  <p class="small text-muted mb-0">Followers</p>
                </div>
                <div>
                  <p class="mb-1 h5">478</p>
                  <p class="small text-muted mb-0">Following</p>
                </div>
              </div>
            </div>
            <div class="card-body p-4 text-black">
              <div class="mb-5">
                <p class="lead fw-normal mb-1">About</p>
                <div class="p-4" style="background-color: #f8f9fa">
                  {{profile.about|safe}}
                  <p class="font-italic mb-1">Web Developer</p>
                  <p class="font-italic mb-1">Lives in New York</p>
                  <p class="font-italic mb-0">Photographer</p>
                </div>
              </div>
              <div class="mb-5">
                <p class="lead fw-normal mb-1">Contact</p>
                <div class="p-4" style="background-color: #f8f9fa">
                  <p class="font-italic mb-1">
                    Phone
                    <a href="tel:+{{user.profile.phone}}"
                      >{{user.user_profile.phone}}</a
                    >
                  </p>
                  <p class="font-italic mb-1">
                    Mail: <a href="mailto:{{user.email}}">{{user.email}}</a>
                  </p>
                  <p class="font-italic mb-0">Photographer</p>
                </div>
              </div>
              <div
                class="d-flex justify-content-between align-items-center mb-4"
              >
                <p class="lead fw-normal mb-0">Recent photos</p>
                <p class="mb-0">
                  <a href="#!" class="text-muted">Show all</a>
                </p>
              </div>
              <div class="row g-2">
                <div class="col mb-2">
                  <img
                    src="https://mdbcdn.b-cdn.net/img/Photos/Lightbox/Original/img%20(112).webp"
                    alt="image 1"
                    class="w-100 rounded-3"
                  />
                </div>
                <div class="col mb-2">
                  <img
                    src="https://mdbcdn.b-cdn.net/img/Photos/Lightbox/Original/img%20(107).webp"
                    alt="image 1"
                    class="w-100 rounded-3"
                  />
                </div>
              </div>
              <div class="row g-2">
                <div class="col">
                  <img
                    src="https://mdbcdn.b-cdn.net/img/Photos/Lightbox/Original/img%20(108).webp"
                    alt="image 1"
                    class="w-100 rounded-3"
                  />
                </div>
                <div class="col">
                  <img
                    src="https://mdbcdn.b-cdn.net/img/Photos/Lightbox/Original/img%20(114).webp"
                    alt="image 1"
                    class="w-100 rounded-3"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock content %}
</div>
{% block JS %} {% endblock JS %}

templates/users/profile_update.html
{% extends '../index.html' %} {% block css %}
<style>
  .register-form {
    max-width: 720px;
  }
</style>
{% endblock css %} {% load crispy_forms_tags %} 
{%block title%}Register{%endblock title %}
<div>
  {% block content %}
  <div class="container row d-flex justify-content-center">
    <form
      method="POST"
      class="form-group col-md-6 my-3 register-form"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <h2 class="text-center">Profile info</h2>
      {{ u_form|crispy }} {{p_form.media}} {{ p_form|crispy }}
      <div>
        <button type="submit" class="btn btn-success">Update</button>
      </div>
    </form>
  </div>
  {% endblock content %}
</div>
{% block JS %}
<script>
  // $(document).ready(function () {
  //   $("#id_date_of_birth").attr("type","date")
  // });
</script>
{% endblock JS %}